[package]
name = "starts-bevy-engine"
version = "0.2.0"
edition = "2024"
resolver = "3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.16" }

[profile.dev.package."*"]
opt-level = 3

